window.GoSquared||(GoSquared={});
(function(){var k=true,l=null,m=false;function p(a){this.c=a;this.h=m}var e={V:"cluster-0.gosquared.com/info",ea:"cluster-0.gosquared.com/ping"};e.d=function(){function a(d,b){return new c(d,b)}function c(d,b){this.f=d;this.D=b}this.G=[a("google","q"),a("yahoo","p"),a("msn","q"),a("aol","query"),a("aol","encquery"),a("lycos","query"),a("ask","q"),a("altavista","q"),a("netscape","query"),a("cnn","query"),a("looksmart","qt"),a("about","terms"),a("mamma","query"),a("alltheweb","q"),a("gigablast","q"),a("voila","rdata"),a("virgilio",
"qs"),a("live","q"),a("baidu","wd"),a("alice","qs"),a("yandex","text"),a("najdi","q"),a("aol","q"),a("club-internet","q"),a("mama","query"),a("seznam","q"),a("search","q"),a("wp","szukaj"),a("onet","qt"),a("netsprint","q"),a("google.interia","q"),a("szukacz","q"),a("yam","k"),a("pchome","q"),a("bing","q")];this.w="/";this.I="gs_u";this.Z=2147483647;this.oa=GoSquared.na===undefined?k:GoSquared.na;this.r=GoSquared.r===undefined?m:GoSquared.r;this.g=GoSquared.g===undefined?200:GoSquared.g};e.z=function(a){function c(f){var h=
new Date;return"expires="+(new Date(h.getTime()-h.getTime()%864E5+f*1E3)).toGMTString()+"; "}function d(){return"expires="+(new Date((new Date).getTime()+6E4)).toGMTString()+"; "}function b(){return c(86400)}function i(){return c(63072E3)}function g(){var f=document.domain;if("www."==f.substring(0,4))f=f.substring(4);return"domain="+f+";"}var j=new e.d;this.H=function(f,h){var o=i;if(l==h)return this.wa(f);if(undefined==a||!a||"day"==a.toLowerCase())o=b;if(a=="minute")o=d;document.cookie=[f,"=",h,
";",o(),"path="+j.w+";",g()].join("")};this.A=function(f){for(var h=f+"=",o=h.length,q=document.cookie.length,n=0;n<q;){f=n+o;if(document.cookie.substring(n,f)==h){h=document.cookie.indexOf(";",f);if(h==-1)h=document.cookie.length;return unescape(document.cookie.substring(f,h))}n=document.cookie.indexOf(" ",n)+1;if(n==0)break}return l};this.Q=function(f){document.cookie=[f,"=;expires=Thu, 01-Jan-1970 00:00:01 GMT;","path="+j.w+";",g()].join("")}};e.xa=function(a,c){var d=encodeURIComponent;return d instanceof
Function?c?encodeURI(a):d(a):escape(a)};e.P=function(a,c){var d=decodeURIComponent;return d instanceof Function?c?decodeURI(a):d(a):unescape(a)};e.ja=function(){return Math.round(Math.random()*(new e.d).Z)};e.ra=function(a,c,d){var b=new e.z("infinite"),i=new e.d,g=b.A(i.I),j=1,f=1;this.F=k;this.B=0;if(g==l||!g.match(/^[0-9\:]*$/)){this.F=m;g=e.ja()}else{var h=g.split(":");g=h[0];if(h.length==1){h[1]=2019;h[2]=4621}if(h.length==3)h[3]=0;j=(h[1]-2019)/548;f=(h[2]-4621)/379;this.B=h[3];f+=1;if(c)j+=
1}b.H(i.I,g+":"+(2019+548*j)+":"+(4621+379*f)+":"+(new Date).getTime());this.id=g;this.sa=j;this.ha=f;c=b.A("gs_p_"+a.c);if(l!=c){this.q=c;b.Q("gs_p_"+a.c)}if(d)this.q=a.id};e.J=function(a,c){var d=new e.d;this.ca=function(b){if(undefined!=b&&""!=b){if(b.indexOf("://")>0){b=b.substring(b.indexOf("://")+3);if(b.indexOf("/")>0)return b.substring(b.indexOf("/"));return""}return b}b=document.location.pathname;if(d.oa)b+=document.location.search;if(d.r)b+=document.location.hash;return b}(a);this.ka=c!==
undefined?c:document.title;this.R=function(b){if(b!==undefined&&b.indexOf("://")>0)return b=b.split("://")[1].split("/")[0];return b=document.domain}(a);this.ga=function(b){if(b!==undefined&&b.indexOf("://")>0)return b=b.split("://")[0]+":";return b=document.location.protocol}(a);this.fa=function(){if(window._gstc_s!==undefined&&window._gstc_lt!==undefined){var b=window._gstc_lt-window._gstc_s;return b}return b=0}();this.ma=function(){if(window._gstc_lt!==undefined){var b=+new Date-window._gstc_lt-
GoSquared.TrackDelay;return b}return b=0}();this.W="file:"==document.location.protocol};e.K=function(){var a=function(){var c=document.referrer,d=document.domain,b=m;if(undefined==c||""==c)c="-";else{d=c.split("://")[1].toLowerCase().indexOf(d.toLowerCase());b=d>=0&&d<=8?k:m;c="["==c.charAt(0)&&"]"==c.charAt(c.Ca-1)?"-":c}return{i:b,path:c}}();this.url=a.path;this.i=a.i;this.p=function(c){var d=new e.d;if("-"==c)return l;var b=c.split("://")[1].toLowerCase();if(b.indexOf("/"))b=b.split("/")[0];for(var i=
0;i<d.G.length;i+=1){var g=d.G[i];if(b.indexOf(g.f.toLowerCase())>-1){c=c.split("?").join("&");if(c.indexOf("&"+g.D+"=")>-1){c=c.split("&"+g.D+"=")[1];if(c.indexOf("&")>-1)c=c.split("&")[0];return{f:g.f,ia:e.P(c)}}}}return l}(a.path)};e.M=function(){this.l={s:0,o:0};this.v="-";if(self.screen){this.l={s:screen.width,o:screen.height};this.v=screen.colorDepth}else if(self.Ba)try{var a=java.ua.ta.za().Aa();this.l={s:a.width,o:a.height}}catch(c){}this.Y=(navigator.language?navigator.language:navigator&&
navigator.browserLanguage?navigator.browserLanguage:"-").toLowerCase();this.X=navigator.javaEnabled();this.N=document.characterSet?document.characterSet:document.charset?document.charset:"-";this.U=function(){var d=navigator;if(d&&d.plugins&&d.plugins.length>0)for(var b=0;b<d.plugins.length;b++){var i=d.plugins[b];if(i.name.indexOf("Shockwave Flash")>-1)return i.description.split("Shockwave Flash ")[1]}else if(window.ActiveXObject)for(d=11;d>=2;d--)try{this.Da=(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+
d))&&b.va;if(b)return d+".0"}catch(g){}return"-"}()};e.u=function(a){function c(g){var j=[],f;for(f in g)j.push(encodeURIComponent(f)+"="+encodeURIComponent(g[f]));return j.join("&")}a.separator=a.separator==undefined?"?":a.separator;a.data=typeof a.data=="object"?a.separator+c(a.data):typeof a.data=="string"&&a.data.length>0&&a.data.ya(0)=="?"?a.data:a.data?"?"+a.data:"";if(!a.data)a.data="";a.m=a.m||function(){};var d=document.getElementsByTagName("head")[0],b=document.createElement("script");b.src=
document.location.protocol+"//"+a.url+a.data;var i=m;b.onload=b.onreadystatechange=function(){if(!i&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){i=k;a.m();d.removeChild(b);b=l}};d.appendChild(b)};e.j=function(a,c,d){if(!a.ba){c=undefined===c?a.h?"focus":"blur":c;c="/"+c;if(!a.k)a.k=0;a.k+=1;e.u({url:e.ea+"/"+a.c+"/"+a.qa+"/"+a.id+"/"+Math.round((new Date).getTime()/1E4%1E3)+c,m:function(){if(GoSquared.needsRePing){a.TrackView();delete GoSquared.needsRePing}if(GoSquared.pingSuccess===
k){var b=2E4;if(GoSquared.nextPing){b=GoSquared.nextPing*1E3;delete GoSquared.nextPing}a.k=0;clearTimeout(a.b);a.b=setTimeout(function(){e.j(a)},b);delete GoSquared.pingSuccess}else GoSquared.pingSuccess===m&&clearTimeout(a.b)},data:d,separator:d==undefined?undefined:"/"});if(a.k<5){clearTimeout(a.b);a.b=setTimeout(function(){e.j(a)},1E4)}a.O=(new Date).getTime()}};e.t=function(a){a.h=k};e.n=function(a){a.h=m};e.S=function(a,c,d){if(typeof d=="string")d={caption:d};d.gs_evt_name=c;for(var b in d)d[b]=
encodeURIComponent(d[b]);e.j(a,"event",d)};e.da=function(a){(new e.z("minute",(new Date).getTime())).H("gs_p_"+a.c,a.id);return k};e.aa=function(a){if(a.h)return k;e.t(a);clearTimeout(a.C);a.C=setTimeout(function(){e.n(a)},6E4)};e.L=function(a){a.$=function(){e.aa(a)};e.e(document,"mousemove",a.$);a.C=setTimeout(function(){e.n(a)},6E4)};e.e=function(a,c,d){if(a.addEventListener)a.addEventListener(c,d,m);else a.attachEvent&&a.attachEvent("on"+c,d)};e.Ea=function(a,c,d){if(a.removeEventListener)a.removeEventListener(c,
d,m);else a.detachEvent&&a.detachEvent("on"+c,d)};p.prototype.c="";p.prototype.TrackView=function(a,c){var d=new e.d,b=new e.J(a,c);if(b.W)return m;var i=new e.K,g=new e.ra(this,!i.i,a!==undefined),j=new e.M;b={a:this.c,cs:j.N,cd:j.v,fl:j.U,je:j.X?1:0,la:j.Y,sw:j.l.s,sh:j.l.o,dm:b.R,pa:b.ca,pt:b.ka,pr:b.ga,pl:b.fa,tl:b.ma,ri:i.i?1:0,ru:i.url,ui:g.id,re:g.F?1:0,vi:g.sa,pv:g.ha,lv:g.B};if(d.g!=200)b.ec=d.g;this.qa=g.id;if(GoSquared.UserName!=undefined)b.un=GoSquared.UserName;else if(GoSquared.VisitorName!=
undefined)b.un=GoSquared.VisitorName;if(l!=i.p){b.oe=i.p.f;b.ok=i.p.ia}if(l!=g.q)b.pp=g.q;if(l!=this.id&&a===undefined)b.id=this.id;this.b=0;var f=this;e.u({url:e.V,data:b,m:function(){if(GoSquared.overLimit)f.ba=k;else{f.id=GoSquared.id;delete GoSquared.id;f.b!=0&&clearTimeout(f.b);f.b=setTimeout(function(){e.j(f)},2E4);e.e(window,"beforeunload",function(){e.da(f)})}}});l==this.id&&setTimeout(function(){e.e(window,"focus",function(){e.t(f)});e.e(window,"blur",function(){e.n(f)});e.L(f)},500);this.O=
(new Date).getTime()};p.prototype.TrackEvent=function(a,c){e.S(this,a,c)};GoSquared.Tracker=function(a,c){if(c===undefined)c="DefaultTracker";GoSquared[c]&&GoSquared[c].T&&clearTimeout(GoSquared[c].T);return new p(a)};if(GoSquared.TrackDelay===undefined)GoSquared.TrackDelay=50;GoSquared.DefaultTracker=GoSquared.Tracker(GoSquared.acct);GoSquared.DefaultTracker.T=setTimeout(function(){GoSquared.DefaultTracker.TrackView()},GoSquared.TrackDelay)})();