// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN			1001
#define IDR_ICO_MAIN		8001

#define ID_TEXT_SLIDER_R	4001
#define ID_TEXT_SLIDER_G	4003
#define ID_TEXT_SLIDER_B	4005
#define ID_TEXT_CHOOSE		4009
#define ID_TEXT_COPY		4007
#define ID_TEXT_VALUE_HTML	4023

#define ID_BG_SLIDER_R		4011
#define ID_BG_SLIDER_G		4013
#define ID_BG_SLIDER_B		4015
#define ID_BG_CHOOSE		4017
#define ID_BG_COPY			4008
#define ID_BG_VALUE_HTML	4024

#define ID_VIEWER			4021
