//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalizationSample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalizationSample.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalization  Application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish, Denmark.
        /// </summary>
        public static string LangRegionNameDaDK {
            get {
                return ResourceManager.GetString("LangRegionNameDaDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German, Germany.
        /// </summary>
        public static string LangRegionNameDe {
            get {
                return ResourceManager.GetString("LangRegionNameDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English, United Kingdom.
        /// </summary>
        public static string LangRegionNameEnUK {
            get {
                return ResourceManager.GetString("LangRegionNameEnUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English, United States.
        /// </summary>
        public static string LangRegionNameEnUS {
            get {
                return ResourceManager.GetString("LangRegionNameEnUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish, Spain.
        /// </summary>
        public static string LangRegionNameEs {
            get {
                return ResourceManager.GetString("LangRegionNameEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French, France.
        /// </summary>
        public static string LangRegionNameFr {
            get {
                return ResourceManager.GetString("LangRegionNameFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian, Italy.
        /// </summary>
        public static string LangRegionNameIt {
            get {
                return ResourceManager.GetString("LangRegionNameIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string MenuItemText {
            get {
                return ResourceManager.GetString("MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort:.
        /// </summary>
        public static string SortText {
            get {
                return ResourceManager.GetString("SortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Format:.
        /// </summary>
        public static string TextLabelCurrency {
            get {
                return ResourceManager.GetString("TextLabelCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Language:.
        /// </summary>
        public static string TextLabelDispLang {
            get {
                return ResourceManager.GetString("TextLabelDispLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Date format:.
        /// </summary>
        public static string TextLabelLngDate {
            get {
                return ResourceManager.GetString("TextLabelLngDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Time Format:.
        /// </summary>
        public static string TextLabelLngTime {
            get {
                return ResourceManager.GetString("TextLabelLngTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Locale:.
        /// </summary>
        public static string TextLabelLocale {
            get {
                return ResourceManager.GetString("TextLabelLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Format:.
        /// </summary>
        public static string TextLabelRegionFormat {
            get {
                return ResourceManager.GetString("TextLabelRegionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Date Format:.
        /// </summary>
        public static string TextLabelShrtDate {
            get {
                return ResourceManager.GetString("TextLabelShrtDate", resourceCulture);
            }
        }
    }
}
