// INCLUDE FILE generated by "Pelles C for Windows, version 2.73".

#define IDR_ICON1  8001
#define DLG_MAIN  1001
#define EDIT_CONTROL  4001
#define IDSAVEAS    4002

#define DLG_FUNCLIST  1002
#define LST_FUNCTIONS  4003
#define CHK_LIST_SORTED  4005
#define BTN_FUNCTION_BEGIN  4004
#define BTN_FUNCTION_END  4006
#define LST_FUNCTIONS_SORTED  4007
