timeserv: timeserv.o helper.o
	gcc -o timeserv timeserv.o helper.o -Wall

timeserv.o: timeserv.c helper.h
	gcc -o timeserv.o timeserv.c -c -ansi -pedantic -Wall

helper.o: helper.c helper.h
	gcc -o helper.o helper.c -c -ansi -pedantic -Wall









