// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define IDR_BMP_BANNER  8001
#define IDR_BMP_FINISH  8002
#define DLG_START  1001
#define DLG_FINISH  1002
#define DID_SIMPLE  4001
#define DID_HELLO  4002
#define DID_RESULTFILES  4003
#define DID_PROJFOLDER  4004
#
#define IDR_MAIN_C  8003
#define IDR_MAIN_H  8004
#define IDR_MAIN_RC  8005
#define IDR_MAIN_ICO  8006
#define DID_DISPNAME  4005
#define IDS_APPLICATION  10001

