// INCLUDE FILE generated by "Pelles C for Windows, version 4.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define MENU_BAR  2001
#define MENU_SALIR  6001
#define ACCEL_TAB  3001
#define MSG_TAB  1
#define CTL_STSBAR  4001
#define CTL_LSTVIW  4002
#define SQL_SENTENCE  4004
#define DLG_TABLE 9000
#define DLG_STSBAR 9001
#define IDB_EXECUTE  4003
#define IDC_CONNECT  4005
#define IDL_WARNING  4006

