/*{"created":"2010-08-06T16:00:16Z","mac":"1:32a86bcdb62e7c464a0ed84d3a5711dd429315b86911a5e5b36f9e3fbc82f236","k":"0.7.6","version":"656314"}*/
;(function(window,document,undefined){
function g(a){return function(){return this[a]}}function h(a,b){this.n=a;this.e=b}h.prototype.createElement=function(a,b,c){a=this.n.createElement(a);if(b)for(var d in b)if(b.hasOwnProperty(d))if(d=="style"&&this.e.getName()=="MSIE")a.style.cssText=b[d];else a.setAttribute(d,b[d]);c&&a.appendChild(this.n.createTextNode(c));return a};function i(a,b,c){a=a.n.getElementsByTagName(b)[0];if(!a)a=document.documentElement;if(a&&a.lastChild){a.insertBefore(c,a.lastChild);return true}return false}
function k(a,b){if(b.parentNode){b.parentNode.removeChild(b);return true}return false}function o(a,b,c){a=b.className.split(/\s+/);for(var d=0,e=a.length;d<e;d++)if(a[d]==c)return;a.push(c);b.className=a.join(" ").replace(/^\s+/,"")}function p(a,b,c){a=b.className.split(/\s+/);for(var d=[],e=0,f=a.length;e<f;e++)a[e]!=c&&d.push(a[e]);b.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}function q(a,b,c,d,e,f,j){this.ca=a;this.la=b;this.X=c;this.W=d;this.fa=e;this.ea=f;this.ma=j}
q.prototype.getName=g("ca");q.prototype.getVersion=g("la");q.prototype.getEngine=g("X");q.prototype.getEngineVersion=g("W");q.prototype.getPlatform=g("fa");q.prototype.getPlatformVersion=g("ea");function r(a){this.e=a}var aa=new q("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",false);r.prototype.parse=function(){return this.e.indexOf("MSIE")!=-1?ba(this):this.e.indexOf("Opera")!=-1?ca(this):this.e.indexOf("AppleWebKit")!=-1?da(this):this.e.indexOf("Gecko")!=-1?ea(this):aa};
function s(a){var b=t(a,a.e,/(iPod|iPad|iPhone|Android)/,1);if(b!="")return b;a=t(a,a.e,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}function u(a){var b=t(a,a.e,/(OS X|Windows NT|Android) ([^;]+)/,2);if(b)return b;if(b=t(a,a.e,/(iPhone )?OS ([\d_]+)/,2))return b;if(a=t(a,a.e,/Linux ([i\d]+)/,1))return a;return"Unknown"}
function ba(a){var b=t(a,a.e,/(MSIE [\d\w\.]+)/,1);if(b!=""){var c=b.split(" ");b=c[0];c=c[1];return new q(b,c,b,c,s(a),u(a),v(a,c)>=6)}return new q("MSIE","Unknown","MSIE","Unknown",s(a),u(a),false)}
function ca(a){var b="Unknown",c="Unknown",d=t(a,a.e,/(Presto\/[\d\w\.]+)/,1);if(d!=""){c=d.split("/");b=c[0];c=c[1]}else{if(a.e.indexOf("Gecko")!=-1)b="Gecko";d=t(a,a.e,/rv:([^\)]+)/,1);if(d!="")c=d}if(a.e.indexOf("Version/")!=-1){d=t(a,a.e,/Version\/([\d\.]+)/,1);if(d!="")return new q("Opera",d,b,c,s(a),u(a),v(a,d)>=10)}d=t(a,a.e,/Opera[\/ ]([\d\.]+)/,1);if(d!="")return new q("Opera",d,b,c,s(a),u(a),v(a,d)>=10);return new q("Opera","Unknown",b,c,s(a),u(a),false)}
function da(a){var b=s(a),c=u(a),d=t(a,a.e,/AppleWebKit\/([\d\.\+]+)/,1);if(d=="")d="Unknown";var e="Unknown";if(a.e.indexOf("Chrome")!=-1)e="Chrome";else if(a.e.indexOf("Safari")!=-1)e="Safari";var f="Unknown";if(a.e.indexOf("Version/")!=-1)f=t(a,a.e,/Version\/([\d\.\w]+)/,1);else if(e=="Chrome")f=t(a,a.e,/Chrome\/([\d\.]+)/,1);var j=t(a,d,/\d+\.(\d+)/,1);return new q(e,f,"AppleWebKit",d,b,c,v(a,d)>=526||v(a,d)>=525&&parseInt(j,10)>=13)}
function ea(a){var b="Unknown",c="Unknown",d=false;if(a.e.indexOf("Firefox")!=-1){b="Firefox";var e=t(a,a.e,/Firefox\/([\d\w\.]+)/,1);if(e!=""){d=t(a,e,/\d+\.(\d+)/,1);c=e;d=e!=""&&v(a,e)>=3&&parseInt(d,10)>=5}}else if(a.e.indexOf("Mozilla")!=-1)b="Mozilla";e=t(a,a.e,/rv:([^\)]+)/,1);if(e=="")e="Unknown";else if(!d){d=v(a,e);var f=parseInt(t(a,e,/\d+\.(\d+)/,1),10),j=parseInt(t(a,e,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&f>9||d==1&&f==9&&j>=2||e.match(/1\.9\.1b[123]/)!=null||e.match(/1\.9\.1\.[\d\.]+/)!=
null}return new q(b,c,"Gecko",e,s(a),u(a),d)}function v(a,b){a=t(a,b,/(\d+)/,1);if(a!="")return parseInt(a,10);return-1}function t(a,b,c,d){if((a=b.match(c))&&a[d])return a[d];return""}function fa(a,b,c,d){this.g=a;this.j=b;this.J=c;this.m=d||ga;this.l=new x("-")}var ga="wf";function z(a,b,c){p(a.g,a.j,a.l.k(a.m,b,c,"loading"));o(a.g,a.j,a.l.k(a.m,b,c,"active"));A(a,"fontactive",b,c)}function B(a){o(a.g,a.j,a.l.k(a.m,"inactive"));A(a,"inactive")}
function ha(a){p(a.g,a.j,a.l.k(a.m,"loading"));o(a.g,a.j,a.l.k(a.m,"active"));A(a,"active")}function A(a,b,c,d){a.J[b]&&a.J[b](c,d)}function C(a,b,c,d,e){this.g=a;this.r=b;this.C=c;this.A=d;this.O=e;this.K=0;this.H=this.R=false;this.ba=new D;this.Y=new E}
C.prototype.watch=function(a,b,c){for(var d=a.length,e=0;e<d;e++){var f=a[e];b[f]||(b[f]=["n4"]);this.K+=b[f].length}if(c)this.R=c;for(e=0;e<d;e++){f=a[e];c=b[f];for(var j=0,y=c.length;j<y;j++){var l=c[j],n=F(this,"_,arial,helvetica",l),w=this.C.D(n);k(this.g,n);n=f;var m=this.r;o(m.g,m.j,m.l.k(m.m,n,l,"loading"));A(m,"fontloading",n,l);m=F(this,this.ba.quote(n),l);if(w!=this.C.D(m)){k(this.g,m);z(this.r,n,l);this.H=true;G(this)}else H(this,this.O(),w,m,n,l)}}};
function G(a){if(--a.K==0&&a.R)a.H?ha(a.r):B(a.r)}C.prototype.V=function(a,b,c,d,e){if(b!=this.C.D(c)){k(this.g,c);z(this.r,d,e);this.H=true;G(this)}else if(this.O()-a<5E3)H(this,a,b,c,d,e);else{k(this.g,c);a=this.r;p(a.g,a.j,a.l.k(a.m,d,e,"loading"));o(a.g,a.j,a.l.k(a.m,d,e,"inactive"));A(a,"fontinactive",d,e);G(this)}};function H(a,b,c,d,e,f){a.A(function(j,y){return function(){y.call(j,b,c,d,e,f)}}(a,a.V),50)}
function F(a,b,c){c=a.Y.expand(c);b=a.g.createElement("span",{style:"position:absolute;top:-999px;font-size:300px;font-family:"+b+",_,arial,helvetica;"+c},"Mm");i(a.g,"body",b);return b}function x(a){this.$=a||ia}var ia="-";x.prototype.k=function(){for(var a=[],b=0;b<arguments.length;b++)a.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.$)};function D(){this.U='"'}
D.prototype.quote=function(a){var b=[];a=a.split(/,\s*/);for(var c=0;c<a.length;c++){var d=a[c].replace(/['"]/g,"");d.indexOf(" ")==-1?b.push(d):b.push(this.U+d+this.U)}return b.join(",")};function E(){this.T=ja;this.s=ka}var ja=["font-style","font-weight"],ka={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function I(a,b,c){this.Z=a;this.ga=b;this.s=c}I.prototype.expand=function(a,b){for(var c=0;c<this.s.length;c++)if(b==this.s[c][0]){a[this.Z]=this.ga+":"+this.s[c][1];return}};E.prototype.expand=function(a){if(a.length!=2)return null;for(var b=[null,null],c=0,d=this.T.length;c<d;c++){var e=this.T[c],f=a.substr(c,1);(new I(c,e,this.s[e])).expand(b,f)}return b[0]&&b[1]?b.join(";")+";":null};function J(a,b){this.n=a;this.e=b}J.prototype=h.prototype;
function K(a){return a.n.location.protocol=="https:"}function L(a,b,c){var d=a.n.getElementsByTagName("head")[0];if(d){var e=a.n.createElement("script");e.src=b;var f=false;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){f=true;c&&c();e.onload=e.onreadystatechange=null;e.parentNode.tagName=="HEAD"&&d.removeChild(e)}};d.appendChild(e)}}
function la(a,b){a=a.n.createElement("style");a.setAttribute("type","text/css");if(a.styleSheet)a.styleSheet.cssText=b;else a.appendChild(document.createTextNode(b));return a}function M(a,b){this.ja=a;this.L=b}function ma(a){for(var b=a.ja.join(","),c=[],d=0;d<a.L.length;d++){var e=a.L[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function N(a,b){this.w=a;this.M=b}N.prototype.watch=function(a,b,c){var d=[],e={};d.push(this.w);e[this.w]=this.M[b.G]||[];a.watch(d,e,c)};
function O(a,b,c){this.ka=a;this.F=b;this.ha=c}function P(a,b,c){b=a.ka&&b?"https:":"http:";var d=typeof a.F=="function"?a.F(b):a.F;return b+"//"+d+a.ha+c}function na(a,b,c){if(a.N){var d=function(){try{b._gat._getTracker("UA-8850781-3")._trackPageview();b.tkKitsTracked||(b.tkKitsTracked=0);b.tkKitsTracked++}catch(e){}};if(b._gat)d();else{a=P(a.N,K(c),"/ga.js");L(c,a,d)}}}function Q(a,b,c){this.o=a;this.G=b;this.Q=c}function R(){this.p=[]}R.prototype.h=function(a){S(this,a.o)||this.p.push(a)};
function S(a,b){for(var c=0;c<a.p.length;c++){var d=a.p[c];if(b===d.o)return d}return null}function T(a,b){for(var c=0;c<a.p.length;c++){var d=a.p[c];if(d.Q?d.Q(b.getName(),b.getVersion(),b.getEngine(),b.getEngineVersion(),b.getPlatform(),b.getPlatformVersion()):false)return d}return null}R.prototype.t=function(a){for(var b=0;b<this.p.length;b++)a.h(this.p[b])};function U(a){this.o=a;this.B=new R;this.q=[];this.v=[]}U.prototype.h=function(a){this.B.h(a)};U.prototype.t=function(a){this.B.t(a)};
function oa(a,b){for(var c=[],d=0;d<a.v.length;d++)c.push(ma(a.v[d]));i(b,"head",la(b,c.join("")))}U.prototype.load=function(a,b,c,d){var e;e=this.ia;var f="/"+this.o+"-"+c.G+".css";if(e)f+="?"+e;e=P(this.da,K(a),f);i(a,"head",a.createElement("link",{rel:"stylesheet",href:e}));if(b)for(a=0;a<this.q.length;a++)this.q[a].watch(b,c,d&&a==this.q.length-1)};
function pa(a,b,c,d){if(a.z){na(a.z,b,d);b=a.z;if(b.S){b=P(b.S,K(d),"/"+a.o+".js?"+ +new Date);L(d,b)}b=a.z;a=a.o;if(b.I){c=b.I.k(a,c,d);c.setAttribute("id","typekit-badge-"+a);i(d,"body",c)}}}function V(a,b,c,d,e){this.aa=a;this.g=b;this.e=c;this.j=d;this.A=e;this.i=[]}V.prototype.u=function(a){this.i.push(a)};
V.prototype.load=function(a,b){a=a;var c=b||{};if(typeof a=="string")a=[a];else if(a&&a.length)a=a;else{c=a||{};a=[]}if(a.length){var d=this,e=a.length;for(b=0;b<a.length;b++)L(this.g,P(this.aa,K(this.g),"/"+a[b]+".js"),function(){--e==0&&qa(d,c)})}else qa(this,c)};
function qa(a,b){if(b.userAgent)a.e=(new r(b.userAgent)).parse();b=new fa(a.g,a.j,b);for(var c=new R,d=0;d<a.i.length;d++)a.i[d].t(c);c=T(c,a.e);for(d=0;d<a.i.length;d++)oa(a.i[d],a.g);if(c){o(b.g,b.j,b.l.k(b.m,"loading"));A(b,"loading");ra(a,c,b)}else B(b);a.i=[]}function ra(a,b,c){c=new C(a.g,c,{D:function(f){return f.offsetWidth}},a.A,function(){return+new Date});for(var d=0;d<a.i.length;d++){var e=a.i[d];if(S(e.B,b.o)){e.load(a.g,c,b,d==a.i.length-1);pa(e,window,a.e,a.g)}}}
function W(a,b){this.P=a;this.g=b;this.i=[]}W.prototype.u=function(a){this.i.push(a)};W.prototype.load=function(){var a=this.P.__webfonttypekitmodule__;if(a)for(var b=0;b<this.i.length;b++){var c=this.i[b],d=a[c.o];if(d){var e=this.g;d(function(f,j,y){var l=new R;c.t(l);j=[];var n={};if(l=T(l,f)){oa(c,e);c.load(e,null,l);for(var w=0;w<c.q.length;w++){var m=c.q[w];j.push(m.w);n[m.w]=m.M[l.G]||[]}pa(c,window,f,e)}y(!!l,j,n)})}}};var X=new R;
X.h(new Q("iphone","f",function(a,b,c,d,e,f){if(e=="iPhone"||e=="iPod")if(b=/^([0-9]+)_([0-9]+)/.exec(f)){a=parseInt(b[1],10);b=parseInt(b[2],10);if(a==3)return b>0;else if(a>3)return true}return false}));X.h(new Q("opera","b",function(a,b){if(a=="Opera")return parseFloat(b)>=10.54;return false}));X.h(new Q("ie","c",function(a,b){if(a=="MSIE"){if(a=/([0-9]+.[0-9]+)/.exec(b))return parseFloat(a[1])>=6;return false}}));
X.h(new Q("safari","b",function(a,b,c,d,e){if(a=="Safari"&&c=="AppleWebKit")if(/Macintosh|Windows/.test(e))if(a=/([0-9]+.[0-9]+)/.exec(d))return parseFloat(a[1])>=525.13;return false}));X.h(new Q("ff35","b",function(a,b,c,d){if(c=="Gecko"){a=/1.9.1b[1-3]{1}/;return/1.9.1/.test(d)&&!a.test(d)}return false}));
X.h(new Q("chrome","b",function(a,b){if(a=="Chrome"){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){a=parseFloat(c[1]);b=parseInt(c[2],10);c=parseInt(c[3],10);if(a>4)return true;else if(a==4&&b>249)return true;else if(a==4&&b==249&&c>=4)return true}}return false}));X.h(new Q("ff36","d",function(a,b,c,d){if(c=="Gecko")if(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(d)){a=parseFloat(b[1]);b=parseInt(b[3],10);return a>1.9||a>=1.9&&b>1}return false}));
X.h(new Q("ipad","f",function(a,b,c,d,e,f){if(e=="iPad")if(b=/^([0-9]+)_([0-9]+)/.exec(f)){a=parseInt(b[1],10);b=parseInt(b[2],10);if(a==3)return b>0;else if(a>3)return true}return false}));if(!window.Typekit){var sa=new O(false,"use.typekit.com","/"),ta=(new r(navigator.userAgent)).parse(),ua=new J(document,ta),Y=new V(sa,ua,ta,document.documentElement,function(a,b){setTimeout(a,b)}),Z=new W(window,ua);window.Typekit=Y;window.Typekit.load=Y.load;window.Typekit.addKit=Y.u}var va,wa,$;
va=new O(false,"use.typekit.com","/k");wa=new function(a,b,c){this.I=a;this.N=b;this.S=c}(void 0,void 0,void 0);$=new U("jad8hru");$.ia="3bb2a6e53c9684ffdc9a9bf01b5b2a62ec6379d745fd2575909b9300bc297f527af58d0cee8e5fd21ed0c17b58e356a1764ee40f09df2e1648f0e59b3a78214e6cd7f7188cd2b34b3bca43b97bc4aed7f3c5aad9843055501778be9d7970659b3192c6dcb14aa7ea3876f77bcaec8c102af6283d1b81eb438af5198043802efe4c4d8bb1f8f44b330cccd1da155e6325c1653332adf39d2d054b3c2c1b48c6e523";$.da=va;$.z=wa;
$.q.push(new N('"museo-slab-1","museo-slab-2"',{a:["n1","i1","n3","i3","n5","i5","n7","i7","n8","i8","n9","i9"],b:["n1","i1","n3","i3","n5","i5","n7","i7","n8","i8","n9","i9"],c:["n5"],d:["n1","i1","n3","i3","n5","i5","n7","i7","n8","i8","n9","i9"],f:["n1","i1","n3","i3","n5","i5","n7","i7","n8","i8","n9","i9"]}));$.q.push(new N('"lobster-1","lobster-2"',{a:["n4"],b:["n4"],c:["n4"],d:["n4"],f:["n4"]}));$.v.push(new M([".tk-museo-slab"],[{value:'"museo-slab-1","museo-slab-2",serif',name:"font-family"}]));
$.v.push(new M([".tk-lobster"],[{value:'"lobster-1","lobster-2",serif',name:"font-family"}]));$.h(S(X,"chrome"));$.h(S(X,"ff35"));$.h(S(X,"ff36"));$.h(S(X,"ie"));$.h(S(X,"ipad"));$.h(S(X,"iphone"));$.h(S(X,"opera"));$.h(S(X,"safari"));if(Z&&Z.P.__webfonttypekitmodule__){Z.u($);Z.load()}else window.Typekit.u($);
})(this,document);