// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".


#define DID_RESULTFILES  4003
#define DID_PROJFOLDER  4004
#
#define IDR_BANNER_BMP  8001
#define IDR_FINISH_BMP  8002
#define IDR_MAIN_C  8003
#define IDR_MAIN_H  8004
#define IDR_MAIN_RC  8005
#define IDR_MAIN_ICO  8006

#define DID_DISPNAME  4005
#define IDS_APPLICATION  10001

#define DLG_START  6001
#define IDWIZLIST 6002

#define DLG_FINISH  7002

