langstrings["ja"] = {
  languagename:"日本語",
  revision:"改訂第@@版",
  credz:"<abbr title=\"ヘンリック・ファルク\">隼変陸</abbr><br/>金山安奈",
  playgame:"試合をする",
  instructions:"説明",
  options:"オプション",
  quit:"閉じる",
  backtomainmenu:"<< メインメニューに戻る",
  back:"<< 戻る",
  choosegametime:"ゲーム時間を選ぶ",
  "2minutes":"　２分間",
  "5minutes":"　５分間",
  "10minutes":"１０分間",
  "20minutes":"２０分間",
  "30minutes":"３０分間",
  playtimeinfo:"強い対戦相手と戦うには最低でもゲーム時間は１０分である必要があります。",
  chooseyourteam:"あなたのチームを選ぶ",
  chooseopponentteam:"対戦相手を選ぶ",
  mustbeat:"このチームで戦うにはこのチームに勝っておく必要があります",
  strength:"強さ:",
  agility:"機敏さ:",
  stamina:"スタミナ:",
  skill:"スキル:",
  tactics:"戦法:",
  returntogame:"ゲームに戻る >>",
  selectonhold:"ボールをもつ選手を自動的に選ぶ",
  selectonpasstarget:"パスのターゲットとなる選手を選ぶ",
  passbeatsselect:"選択した選手がボールを持っている際、他の選手をクリックするとパスではなく、その選手を選ぶことになる",
  checkforupdates:"起動時に修正したゲームが出たかどうかをチェックする",
  language:"言語:",
  runindemomode:"デモ・モード　（パソコン対パソコン）",
  offensive:"攻撃的",
  defensive:"守備的",
  gameover:"ゲームオーバー",
  goals:"ゴール:",
  shots:"ゴールにシュートした回数:",
  possession:"ボール所持率:",
  kickins:"キックイン:",
  finish:"フィニッシュ",
  close:"閉じる",
  options:"オプション",
  latestversion:"最新版",
  updateavailable:"アップデート　有効",
  youwon:"あなたの勝ち!",
  youlost:"あなたの負け!",
  whowon:"@@勝利!",
  kickoff:"キックオフ",
  play:"プレー",
  outoffield:"ボール　場外",
  kickin:"キック・イン",
  goal:"ゴール",
  paused:"停止",
  ended:"終了",
  penguinname:"ペンギンズ",
  penguinshortname:"ペンギンズ",
  piratename:"パイレーツ",
  pirateshortname:"パイレーツ",
  vikingname:"ヴァイキングス",
  vikingshortname:"ヴァイキングス",
  monkeyname:"モンキーズ",
  monkeyshortname:"モンキーズ",
  robotname:"ロボッツ",
  robotshortname:"ロボッツ",
  alienname:"エイリアンズ",
  alienshortname:"エイリアンズ",
  androidname:"アンドロイズ",
  androidshortname:"アンドロイズ",
  ninjaname:"ニンジャズ",
  ninjashortname:"ニンジャズ",
  scriptkidname:"スクリプトキディーズ",
  scriptkidshortname:"スクリプトキッズ",
  monkeydesc:"どうやらモンキーズはチームプレイにおいては進化途上のよう。頭の回転がゆっくりな分、体の動きが速いようです。",
  robotdesc:"元々ブームをねじまげるために作られたロボットたちは強くて几帳面。今ではサッカー用にリモデルされています。",
  androiddesc:"このアンドロイドたちはサッカーのために作られました。体が重くてちょっと遅い分、そのパワーで敵を圧倒させます。彼らの正確さとチームプレイは圧倒的です。",
  ninjadesc:"このよく鍛えられた忍者集団は何か新しい挑戦が必要だと感じたようです。 ボールの扱いは極めていませんが、極めたマーシャルアーツでじゅうぶん補います。",
  vikingdesc:"ヤギ投げでは素晴らしい力を発揮する一方、ヴァイキングたちの世界ではサッカーはスポーツ競技として伝わっていないようです。けれど気力はいつも通り健在。",
  piratedesc:"パイレーツは海沿いの村々を略奪して生計をたてる無法者。サッカーに関しては熱心さもスキルもイマイチのようです。",
  aliendesc:"この宇宙人たちは地球を制服しに来たようです。遺伝子的にも知的にも優れているのですが、なんといっても地球に降り立ったばかりの彼らの辞書にはサッカーという言葉がなさそうです。",
  scriptkiddesc:"この特徴的な子供たちは水銀を喉につまらせてしまってjavascriptの配列で意識を取り戻しました。"
};
