langstrings["en"] = {
  languagename:"English",
  revision:"revision @@",
  credz:"by Henrik Falck<br/>and Anna Kanayama",
  playgame:"Play Game",
  instructions:"Instructions",
  options:"Options",
  quit:"Quit",
  backtomainmenu:"<< back to main menu",
  back:"<< back",
  choosegametime:"Choose game time",
  "2minutes":"2 minutes",
  "5minutes":"5 minutes",
  "10minutes":"10 minutes",
  "20minutes":"20 minutes",
  "30minutes":"30 minutes",
  playtimeinfo:"To face higher-rated teams as opponents and advance in the game, the game time must be at least 10 minutes.",
  chooseyourteam:"Choose your team",
  chooseopponentteam:"Choose opponent team",
  mustbeat:"You must win against this team before it becomes available",
  strength:"Strength:",
  agility:"Agility:",
  stamina:"Stamina:",
  skill:"Skill:",
  tactics:"Tactics:",
  returntogame:"return to game >>",
  selectonhold:"Automatically select player who gets hold of the ball",
  selectonpasstarget:"Select player who is the target of a pass",
  passbeatsselect:"Clicking on a player when the selected player is holding the ball will pass to that player rather than selecting it",
  checkforupdates:"Check for updates at startup",
  language:"Language:",
  runindemomode:"Run in Demo Mode (continuously running computer vs computer)",
  offensive:"Offensive",
  defensive:"Defensive",
  gameover:"Game Over",
  goals:"Goals:",
  shots:"Shots at goal:",
  possession:"Ball possession:",
  kickins:"Kickins caused:",
  finish:"Finish",
  close:"Close",
  options:"Options",
  latestversion:"latest version",
  updateavailable:"Update available",
  youwon:"You won!",
  youlost:"You lost!",
  whowon:"@@ won!",
  kickoff:"kick-off",
  play:"play",
  outoffield:"out of field",
  kickin:"kick-in",
  goal:"goal",
  paused:"paused",
  ended:"ended",
  penguinname:"The Penguins",
  penguinshortname:"Penguins",
  piratename:"The Pirates",
  pirateshortname:"Pirates",
  vikingname:"The Vikings",
  vikingshortname:"Vikings",
  monkeyname:"The Monkeys",
  monkeyshortname:"Monkeys",
  robotname:"The Robots",
  robotshortname:"Robots",
  alienname:"The Aliens",
  alienshortname:"Aliens",
  androidname:"The Androids",
  androidshortname:"Androids",
  ninjaname:"The Ninjas",
  ninjashortname:"Ninjas",
  scriptkidname:"The Script Kiddies",
  scriptkidshortname:"Script Kids",
  monkeydesc:"Apparently, the monkeys have not yet evolved to understand teamplay. However, what they lack in brains they make up for in tails.",
  robotdesc:"Very accurate and quite strong robots originally constructed to contort booms. They have now been remodeled to play soccer.",
  androiddesc:"These androids were built especially for soccer. While their bulk makes them slow, their strength crushes enemies, and their precision and teamplay are flawless.",
  ninjadesc:"This group of highly trained ninja felt they needed a new challenge. Their training in the martial arts more than makes up for not yet having mastered the art of the ball to perfection.",
  vikingdesc:"While excellent at goat throwing, it seems soccer has yet to be introduced as a competitive sport to the Viking lands. But the spirits are high, as always.",
  piratedesc:"The pirates are scurvy swashbucklers who make a living plundering coastal villages and, as such, are not very enthusiastic about, nor skilled at, soccer.",
  aliendesc:"These space aliens have come to take over the planet. Although genetically and intellectually superior, as they have just arrived on Earth, they haven't heard of soccer.",
  scriptkiddesc:"These particular script kiddies choked on a blue pill and woke up outside the javascript array where - as they have come to realize - we all reside. They use their l33t skillz to pwn this game."
};
