/*
* YTPlaylist.com - Instant YouTube Playlist
* Developed by Yumefave team [www.yumefave.com]
* Alex Ho (vnitus) | Steven Ton | Ngoc Tran
* This application utilizes YouTube API
* Contact: yumefave@gmail.com
*/
ymfInclude("http://ytplaylist.com/js/flXHR/flXHR.js","js");ymfInclude("http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js","js");var ymfInitItem="VlOvgDr-M3c",ymfIs=[],ymfHold=[],ymfPl=[],ymfItemsData=[],ymfYtPlayer=[],ymfParams={allowScriptAccess:"always",allowFullScreen:"true"};
function ymfEmbed(a){var b=a.id;this.pl=a.playlist.split(";");ymfPl[b]=this.pl;this.auto=a.auto;this.itemStatus=[];this.itemStatus.play=false;this.itemStatus.mute=false;this.itemStatus.repeat=false;this.itemStatus.shuffle=false;this.itemStatus.reload=false;this.curItemInfo=[];this.curItemInfo.duration=0;this.curItemInfo.currentTime=0;this.curItemInfo.bytesTotal=0;this.curItemInfo.bytesLoaded=0;this.itemsData=[];this.loadCount=0;if(ymfGetEl(b)){a=ymfGetEl(b);a.style.width="725px";a.style.height="344px";
a.style.position="relative"}else{document.write('<div id="'+b+'" style="width:725px;height:344px;margin:0;padding:0;position:relative;"></div>');a=ymfGetEl(b)}var f=ymfCreateEl("ymf_main_"+b,"div");f.style.cssText="width:425px;height:344px;margin:0;padding:0;position:absolute;top:0;left:0;";a.appendChild(f);var h=ymfCreateEl("ymf_yt_player_div_"+b,"div");f.appendChild(h);f=ymfCreateEl("ymf_pl_"+b,"div");f.style.cssText="width:298px;_width:300px;height:342px;_height:344px;margin:0;padding:0;border:1px solid #B3B3B3;position:absolute;top:0;left:425px;";
a.appendChild(f);a=ymfCreateEl("ymf_playlist_"+b,"ul");a.style.cssText="width:298px;height:320px;margin:0;padding:0;list-style-type:none;overflow-x:hidden;overflow-y:scroll;position:absolute;right:0;";a.innerHTML="&nbsp;Loading...";f.appendChild(a);f.innerHTML+='<div style="width:298px;height:21px;background:-moz-linear-gradient(center top,#FFFFFF,#CCCCCC) repeat scroll 0 0 #F6F6F6;background: #F6F6F6 -webkit-gradient(linear,0% 0%,0% 100%,from(white),to(#CCC));margin:0;padding:0;border:0;border-top:1px solid #B3B3B3;overflow-x:hidden;overflow-y:hidden;position:absolute;right:0;bottom:0;"><a href="javascript:ymfBtnPrev(\''+
b+'\');" style="display:block;width:26px;height:15px;line-height:15px;position:absolute;left:0;border:0;border-right:1px solid #B3B3B3;font-family:Arial,Verdana,sans-serif;font-size:12px;text-decoration:none;font-weight:bold;color:#565656;cursor:pointer;padding:3px 5px;text-align:center;" onmouseover="ymfHover(this,\'btn\');" onmouseout="ymfHover(this,\'btn\');">Prev</a><a id="ymf_btn_play_'+b+'" href="javascript:ymfBtnPlay(\''+b+'\');" style="display:block;width:45px;height:15px;line-height:15px;position:absolute;left:37px;border:0;border-right:1px solid #B3B3B3;font-family:Arial,Verdana,sans-serif;font-size:12px;text-decoration:none;font-weight:bold;color:#565656;cursor:pointer;padding:3px;text-align:center;" onmouseover="ymfHover(this,\'btn\');" onmouseout="ymfHover(this,\'btn\');">Play</a><a href="javascript:ymfBtnNext(\''+
b+'\');" style="display:block;width:26px;height:15px;line-height:15px;position:absolute;left:89px;_left:82px;border:0;border-right:1px solid #B3B3B3;font-family:Arial,Verdana,sans-serif;font-size:12px;text-decoration:none;font-weight:bold;color:#565656;cursor:pointer;padding:3px 5px;text-align:center;" onmouseover="ymfHover(this,\'btn\');" onmouseout="ymfHover(this,\'btn\');">Next</a><a id="ymf_btn_repeat_'+b+'" href="javascript:ymfBtnRepeat(\''+b+'\');" style="display:block;width:39px;height:15px;line-height:15px;position:absolute;left:126px;_left:119px;border:0;border-right:1px solid #B3B3B3;font-family:Arial,Verdana,sans-serif;font-size:12px;text-decoration:none;font-weight:bold;color:#565656;cursor:pointer;padding:3px 5px;text-align:center;" onmouseover="ymfHover(this,\'btn\');" onmouseout="ymfHover(this,\'btn\');">Repeat</a><a id="ymf_btn_shuffle_'+
b+'" href="javascript:ymfBtnShuffle(\''+b+'\');" style="display:block;width:39px;height:15px;line-height:15px;position:absolute;left:176px;_left:169px;border:0;border-right:1px solid #B3B3B3;font-family:Arial,Verdana,sans-serif;font-size:12px;text-decoration:none;font-weight:bold;color:#565656;cursor:pointer;padding:3px 5px;text-align:center;" onmouseover="ymfHover(this,\'btn\');" onmouseout="ymfHover(this,\'btn\');">Shuffle</a><a style="display:block;width:60px;_width:79px;height:21px;margin:0;padding:3px 0 0 7px;_padding-left:10px;position:absolute;left:226px;_left:220px;overflow:hidden;" href="http://ytplaylist.com" title="Powered by YTPlaylist.com"><img style="width:58px;height:15px;margin:0;border:0;" src="http://www.ytplaylist.com/img/ytp_logo_embed.png"/></a></div>';
this.curItem=this.pl[0]?this.pl[0]:ymfInitItem;ymfIs[b]=this;this.init=function(){ymfHold["swfobject_"+b]=window.setInterval("ymfLoadSwfobject('"+b+"','"+this.curItem+"')",100)};this.loadFlensed=function(){ymfHold["flensed_"+b]=window.setInterval("ymfLoadFlensed('"+b+"')",100)};this.loadFirstLi=function(){ymfHold["first_li_"+b]=window.setInterval("ymfLoadFirstLi('"+b+"')",100);for(var e in this.pl)this.addItem(this.pl[e])};this.loadYTPlayer=function(){ymfHold["yt_player_"+b]=window.setInterval("ymfLoadYTPlayer('"+
b+"')",100)};this.addItem=function(e){var d=new flensed.flXHR({autoUpdatePlayer:true});d.instanceId="ymfProxy_"+b;d.id=b;ymfItemsData[d.id]=[];ymfItemsData[d.id].count=0;d.loadCount=0;d.xmlResponseText=false;d.onreadystatechange=function(c){var g="",l="",m="",i="",j=0,k=0;if(c.readyState==4)if(k=eval("("+c.responseText+")").data){g=k.id;l=k.title;m=k.uploader;i=k.thumbnail.sqDefault;j=k.viewCount;k=k.duration;c=[];c.title=l;c.author=m;c.thumbnail=i;c.views=j;c.duration=k;ymfItemsData[d.id][g]=c;ymfItemsData[d.id].count++;
ymfItemsData[d.id].count==ymfPl[d.id].length&&ymfIs[d.id].renderPlaylist(d.id)}};d.open("GET","http://gdata.youtube.com/feeds/api/videos/"+e);d.send("alt=jsonc&v=2")};this.renderPlaylist=function(e){var d=ymfGetEl("ymf_playlist_"+e),c="",g="",l="",m="",i=0,j=0;d.innerHTML="";for(var k in ymfPl[e]){c=ymfPl[e][k];j=ymfItemsData[e][c];g=j.title;l=j.author;m=j.thumbnail;i=ymfAddCommasToNumber(j.views);j=ymfConvertTime(j.duration);c='<li id="ymf_item_'+e+"_"+c+'" style="width:100%;margin:0 0 2px 0;padding:5px 5px 0 5px;background-color:#FFFFFF;cursor:pointer;" onmouseover="ymfHover(this,\'li\');" onmouseout="ymfHover(this,\'li\');">'+
ymfIs[e].itemContent(c,g,l,m,i,j)+"</li>";d.innerHTML+=c}};this.itemContent=function(e,d,c,g,l,m){var i=d.length>40?d.substring(0,d.substring(0,41).lastIndexOf(" "))+"...":d;return"<a href=\"javascript:ymfItemClick('"+b+"','"+e+'\')" style="color:#0033CC;text-decoration:none;display:block;cursor:pointer;">\t<p style="margin:0 0 5px 0;_margin-bottom:0;padding:3px;float:left;position:relative;background:#FFF;border:1px solid #D3D3D3;display:block;"><img src="'+g+'" style="width:96px;height:54px;border:none;list-style-type: none;border-bottom-style:none;border-right-style:none;border-top-style:none;border-left-style:none;border:1px solid #D3D3D3;padding:0;"/><span style="position:absolute;right:6px;bottom:6px;background:#000;color:#FFF;font-size:11px;font-weight:bold;height:14px;line-height:14px;opacity:0.75;padding:0 4px;">'+
m+'</span></p>\t<p style="margin:0 0 0 8px;padding:0;float:left;position:relative;"><span style="color:#0033CC;font-size:15px;display:block;width:157px;overflow:hidden;max-height:36px;line-height:1.2;margin-bottom:2px;" title="'+d+'">'+i+'</span>\t<span style="color:#666;display:block;font-size:15px;height:1.4em;line-height:1.4em;overflow:hidden;">by '+c+'</span>\t<span style="color:#666;display:block;font-size:15px;height:1.4em;line-height:1.4em;overflow:hidden;">'+ymfAddCommasToNumber(l)+' views</span></p></a><div style="clear:both;"></div>'};
this.stateChange=function(e){e==0&&this.nextItem();if(e==1){this.itemStatus.play=true;ymfSetEl("ymf_btn_play_"+b,"Pause")}else{this.itemStatus.play=false;ymfSetEl("ymf_btn_play_"+b,"Play")}};this.playVideo=function(){var e=ymfYtPlayer[b];e&&e.playVideo()};this.pauseVideo=function(){var e=ymfYtPlayer[b];e&&e.pauseVideo()};this.prevItem=function(){var e=this.getPrevItem(this.curItem);if(e!==false){this.switchVideo(e);this.curItem=e}else alert("no_prev_item")};this.getPrevItem=function(e){var d=false;
if(this.pl.length==1)d=e;else if(this.pl.length>1)for(var c=0;c<this.pl.length;c++)if(this.pl[c]==e)d=c==0?this.pl[this.pl.length-1]:this.pl[c-1];return d};this.nextItem=function(){var e=ymfGetEl("ymf_yt_player_"+b).data,d="",c=ymfGetEl("ymf_yt_player_"+b).getElementsByTagName("param"),g;for(g in c)if(c[g].name=="movie")d=c[g].value;c=this.itemStatus.shuffle?this.pl[Math.floor(Math.random()*this.pl.length)]:this.itemStatus.repeat?this.curItem:this.getNextItem(this.curItem);if(c!==false){if(c==this.curItem)(e+
d).indexOf("loop=1")<0&&this.reloadSwf("ymf_yt_player_"+b,"ymf_yt_player_div_"+b,c,{enablejsapi:1,playerapiid:"ymfYtPlayer"+b,fs:1,rel:0,showsearch:0,showinfo:0,iv_load_policy:3,autoplay:1,loop:1});else(e+d).indexOf("loop=1")>0&&this.reloadSwf("ymf_yt_player_"+b,"ymf_yt_player_div_"+b,c,{enablejsapi:1,playerapiid:"ymfYtPlayer"+b,fs:1,rel:0,showsearch:0,showinfo:0,iv_load_policy:3,autoplay:1});this.switchVideo(c)}else alert("no_next_item")};this.getNextItem=function(e){var d=false;if(this.pl.length==
1)d=e;else if(this.pl.length>1)for(var c=0;c<this.pl.length;c++)if(this.pl[c]==e)d=c==this.pl.length-1?this.pl[0]:this.pl[c+1];return d};this.switchVideo=function(e){var d=ymfYtPlayer[b];d&&d.cueVideoById(e);if(ymfGetEl("ymf_item_"+b+"_"+this.curItem)!==null)ymfGetEl("ymf_item_"+b+"_"+this.curItem).style.backgroundColor="#FFFFFF";ymfGetEl("ymf_item_"+b+"_"+e).style.backgroundColor="#D1E1FA";this.playVideo();this.curItem=e;this.curItemInfo.duration=0;this.curItemInfo.currentTime=0;this.curItemInfo.bytesTotal=
0;this.curItemInfo.bytesLoaded=0};this.reloadSwf=function(e,d,c,g){var l=[],m="",i;for(i in g)l.push(i+"="+g[i]);m=l.join("&");ymfReplaceSwfWithEmptyDiv(e,d);swfobject.embedSWF("http://www.youtube.com/v/"+c+"?"+m,"ymf_yt_player_div_"+b,"425","344","8",null,null,ymfParams,{id:"ymf_yt_player_"+b});this.itemStatus.reload=true}}
function ymfLoadSwfobject(a,b){if(typeof swfobject!="undefined"){window.clearInterval(ymfHold["swfobject_"+a]);swfobject.embedSWF("http://www.youtube.com/v/"+b+"?enablejsapi=1&playerapiid=ymfYtPlayer"+a+"&fs=1&rel=0&showsearch=0&showinfo=0&iv_load_policy=3","ymf_yt_player_div_"+a,"425","344","8",null,null,ymfParams,{id:"ymf_yt_player_"+a});ymfIs[a].loadFlensed()}}
function ymfLoadFlensed(a){if(typeof flensed!="undefined"){window.clearInterval(ymfHold["flensed_"+a]);ymfIs[a].loadFirstLi();ymfIs[a].loadYTPlayer()}}function ymfLoadFirstLi(a){var b=ymfGetEl("ymf_item_"+a+"_"+ymfIs[a].curItem);if(b){window.clearInterval(ymfHold["first_li_"+a]);b.style.cssText+=";background:#D1E1FA"}}function ymfLoadYTPlayer(a){var b=ymfIs[a];if(ymfYtPlayer[a]){window.clearInterval(ymfHold["yt_player_"+a]);typeof b.auto!="undefined"&&b.auto===true&&b.playVideo()}}
function ymfHover(a,b){var f=a.style.backgroundColor;switch(b){case "li":if(f=="#ffffff"||f=="rgb(255, 255, 255)"||f=="#FFFFFF")a.style.backgroundColor="#D1E1FB";else if(f=="#d1e1fb"||f=="rgb(209, 225, 251)"||f=="#D1E1FB")a.style.backgroundColor="#FFFFFF";break;case "btn":if(f=="")a.style.backgroundColor="#DDDDDD";else if(f=="#dddddd"||f=="rgb(221, 221, 221)"||f=="#DDDDDD")a.style.backgroundColor=""}}
function ymfItemClick(a,b){var f=ymfIs[a],h=ymfYtPlayer[a];if(b==f.curItem)if(h&&h.getPlayerState()==1)h.pauseVideo();else{h&&h.getPlayerState();h.playVideo()}else f.switchVideo(b)}function ymfBtnPrev(a){ymfIs[a].prevItem()}function ymfBtnPlay(a){var b=ymfIs[a];ymfGetEl("ymf_btn_play_"+a).innerHTML=="Play"?ymfSetEl("ymf_btn_play_"+a,"Pause"):ymfSetEl("ymf_btn_play_"+a,"Play");if(b.itemStatus.play){b.itemStatus.play=false;b.pauseVideo()}else{b.itemStatus.play=true;b.playVideo()}}
function ymfBtnNext(a){var b=ymfIs[a];b.itemStatus.repeat&&ymfBtnRepeat(a);b.nextItem()}function ymfBtnRepeat(a){var b=ymfIs[a];if(b.itemStatus.repeat){b.itemStatus.repeat=false;ymfGetEl("ymf_btn_repeat_"+a).style.backgroundColor=""}else{b.itemStatus.repeat=true;ymfGetEl("ymf_btn_repeat_"+a).style.backgroundColor="#D1E1FA";if(b.itemStatus.shuffle){b.itemStatus.shuffle=false;ymfGetEl("ymf_btn_shuffle_"+a).style.backgroundColor=""}}}
function ymfBtnShuffle(a){var b=ymfIs[a];if(b.itemStatus.shuffle){b.itemStatus.shuffle=false;ymfGetEl("ymf_btn_shuffle_"+a).style.backgroundColor=""}else{b.itemStatus.shuffle=true;ymfGetEl("ymf_btn_shuffle_"+a).style.backgroundColor="#D1E1FA";if(b.itemStatus.repeat){b.itemStatus.repeat=false;ymfGetEl("ymf_btn_repeat_"+a).style.backgroundColor=""}}}
function onYouTubePlayerReady(a){a=decodeURIComponent(a.substr(11));var b=ymfIs[a];if(!ymfYtPlayer[a]||b.itemStatus.reload){if(b.itemStatus.reload)b.itemStatus.reload=false;ymfYtPlayer[a]=ymfGetEl("ymf_yt_player_"+a);ymfYtPlayer[a].addEventListener("onStateChange","ymfIs['"+a+"'].stateChange")}}function ymfGetEl(a){return document.getElementById(a)}function ymfSetEl(a,b){ymfGetEl(a).innerHTML=b}function ymfRemoveEl(a){a=ymfGetEl(a);a.parentNode.removeChild(a)}
function ymfCreateEl(a,b){var f=document.createElement(b);f.setAttribute("id",a);return f}function ymfReplaceSwfWithEmptyDiv(a,b){var f=ymfGetEl(a);if(f){var h=document.createElement("div");f.parentNode.insertBefore(h,f);swfobject.removeSWF(a);h.setAttribute("id",b)}}function ymfInclude(a,b){var f=document.getElementsByTagName("body").item(0);if(b=="js"){script=document.createElement("script");script.src=a;script.type="text/javascript";f.appendChild(script)}}
function ymfAddCommasToNumber(a){a+="";x=a.split(".");x1=x[0];x2=x.length>1?"."+x[1]:"";for(a=/(\d+)(\d{3})/;a.test(x1);)x1=x1.replace(a,"$1,$2");return x1+x2}function ymfConvertTime(a){var b=Math.floor(a/60);a=Math.floor(a-b*60);if(a<10)a="0"+a;return b+":"+a};